### PR TITLE
Handle type aliasing for string pointer fields.

### PR DESCRIPTION
**Pull request by dilyevsky**
Useful for some Kubernetes types where field is pointer to string alias.

Example (https://github.com/kubernetes/api/blob/8fc60343b75c9ba9a2b9c7cb5fc3b9c5e9b90158/admissionregistration/v1beta1/types.go#L242):

```
wh = proto.package("k8s.io.api.admissionregistration.v1beta1").Webhook(
    sideEffects = "Some",
)
...
```

(prior to this change would produce crash).

### CODE REVIEW

**Comment by dilyevsky** [comment]
```
go build k8s.io/apimachinery/pkg/api/resource: module requires Go 1.12
```
whaaa?

**Comment by dilyevsky** [comment]
Looks like `js.NewCallback` was deprecated. @jmillikin-stripe PTL

**Comment by dilyevsky** [comment]
Hm I’ll have to somehow fake/mock protobuf msg with all its bells and
whistles (descriptors etc). I’ll see if there’s a good way of doing that

**Comment by jmillikin-stripe** [comment]
I would take a hello world message .pb.go, copy-paste it into the test directory, and edit it to look like a Kubernetes-style message source.

**Comment by dilyevsky** [comment]
Success! It actually needed quite little - main thing was gzipped FileDescriptorProto. @jmillikin-stripe PTAL

**Comment by dilyevsky** [comment]
Thanks!

**Pull request merged**
